---
title: "Final Project: Online Sales Analysis "
authors: "Khushi Satra, 203383100
          Satinder Kaur, 169109308
          Sara Haifa, 169087012
          Spencer Mozeg , 169099531
          Noya Barak, 
---


#Load packages
```{r}
library(tidyverse)
library(tidymodels)
```
#Load datasets
```{r}
Movie_industry<- read.csv("https://raw.githubusercontent.com/khushisatra/Final-Project/refs/heads/main/movies.csv")
Movie_industry
```
{r}
movie_industry <- na.omit(Movie_industry)
movie_industry

#Step 1: Tidying 
```{r}
clean_movie_industry <- movie_industry|>
  mutate(
  released_date = str_extract(released, "^[A-Za-z]+ \\d{1,2}, \\d{4}"),
  hours = runtime%/%60,             
    minutes = runtime %% 60, 
    movie_duration = sprintf("%d hours, %d minutes", hours, minutes),
  genre = as.factor(genre),
  rating = as.factor(rating),
   Profit = gross - budget
  ) |>
  select(-released, -year, -hours, -minutes, -runtime)
clean_movie_industry

```

